In [1]:
import numpy as np
print("w1:",np.array([1,2,3])) #这是数组，中间没有逗号
print("w2:",np.array((4,5,6)))
print("w3:\n",np.array([[1,2,3],[4,5,6]]))
print("w4:\n",np.array([[1,2,3],[4,5,6]],dtype=np.float64))
print("w5:\n",np.arange(10,dtype=np.float64).reshape(2,5))
print("w6:\n",np.arange(0,10,1.0).reshape(2,5))
print("w7:\n",np.arange(0,10,1).reshape(2,5))

w1: [1 2 3]
w2: [4 5 6]
w3:
 [[1 2 3]
 [4 5 6]]
w4:
 [[1. 2. 3.]
 [4. 5. 6.]]
w5:
 [[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]
w6:
 [[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]
w7:
 [[0 1 2 3 4]
 [5 6 7 8 9]]


In [2]:
print("w8:\n",np.linspace(0,10,5))
print("w9:\n",np.logspace(0,1,5))
print("w10:\n",np.zeros(5))
print("w11:\n",np.ones(5))
print("w12:\n",np.ones([5,5]))
print("w13:\n",np.diag(np.ones(5))) #对角线
print("w14:\n",np.eye(5))

w8:
 [ 0.   2.5  5.   7.5 10. ]
w9:
 [ 1.          1.77827941  3.16227766  5.62341325 10.        ]
w10:
 [0. 0. 0. 0. 0.]
w11:
 [1. 1. 1. 1. 1.]
w12:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
w13:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
w14:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [3]:
w_array = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("秩：",w_array.ndim)
print("形状：",w_array.shape)
print("元素个数:",w_array.size)
print(w_array.dtype)
print(w_array.itemsize)

秩： 2
形状： (3, 3)
元素个数: 9
int32
4


In [4]:
w_array = np.array([[1,2,3],[4,5,6]])
print(w_array)
w_array.shape=(3,2)
print(w_array)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [5]:
print(np.random.randint(100,200,5))
print(np.random.rand(3,2))
print(np.random.rand(5))

[100 153 109 156 138]
[[0.2036102  0.19367036]
 [0.28471231 0.75408719]
 [0.99610485 0.45869567]]
[0.42210061 0.97118062 0.72860237 0.06860284 0.83893547]


In [6]:
w_array = np.array([[1,2,3],[4,5,6]])
print(w_array)
print(w_array.reshape(3,2))
w_array = np.arange(8)
print(w_array.reshape(4,2))

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [7]:
arr1 = np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
arr2 = np.arange(9).reshape(3,3)
print(arr1)
print(arr2)
print(arr1+arr2)
print(arr1*arr2)
print(2*arr2)
print(np.hstack((arr1,arr2))) #横向拼接
print(np.vstack((arr1,arr2)))
print(np.concatenate((arr1,arr2),axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]]
[[ 0  2  6]
 [12 20 30]
 [42 56 72]]
[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]
[[1 2 3 0 1 2]
 [4 5 6 3 4 5]
 [7 8 9 6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 2 3 0 1 2]
 [4 5 6 3 4 5]
 [7 8 9 6 7 8]]


In [8]:
arr = np.arange(36).reshape(6, 6)
print(arr)
# print(np.split(arr,3,axis=0))
arr = np.arange(6).reshape(3, 2)
print(arr)
print(arr.T)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
[[0 1]
 [2 3]
 [4 5]]
[[0 2 4]
 [1 3 5]]


In [9]:
arr = np.arange(10)
print(arr)
print(arr[-2::-2])
arr = arr.reshape(2,5)
print(arr[(0,1),(1,3)])

[0 1 2 3 4 5 6 7 8 9]
[8 6 4 2 0]
[1 8]


In [10]:
arr = np.where([[True,False],[True,True]],
               [[1,2],[2,3]],
               [[5,6],[7,8]])
np.save('arr.npy',arr)
print(np.load('arr.npy'))

[[1 6]
 [2 3]]
